// This file is automatically generated and users should not edit it
import type { DduExtType } from "./types.ts";
import type { Mod } from "./loader.ts";

import * as ui_ff from "file:///Users/alisue/.config/nvim/pack/jetpack/opt/ddu-ui-ff/denops/@ddu-uis/ff.ts";

export const mods: Record<DduExtType, Record<string, Mod>> = {
  ui: {
    ff: {
      mod: ui_ff,
      path:
        "/Users/alisue/.config/nvim/pack/jetpack/opt/ddu-ui-ff/denops/@ddu-uis/ff.ts",
    },
  },
  source: {},
  filter: {},
  kind: {},
  column: {},
};
